stringDirt="Hey~ Try to click Dirt in the circle ! Move the mouse to the 3*3 land. Choose one and click it !";
stringCrop="Here is your current plant ! Similarly,click and move to the land which you just added. So easy,right?";
stringHarvest="Look at your crop ! It's ready to be picked. Just click it !";
stringcrop3="Click the left button to see your latest stock.";
stringStockNum="This is the quantity of your harvest.";
stringMenuButton="Click and discover more.";
stringMissionBtn="Click and open the mission.";
stringMissionName="You will get different mission by level.";
stringMissionReq="Fulfill the requirement, get the EXP, and level up ! "
stringMissionExp="";
stringMissionSub="If the condition is satisfied, click the 'SUBMIT' to accomplish the task."
